### ISSUE TITLE
Problem with imports

### ISSUE THREAD

**Issue by filip-machala** [philips558/PPS#1]
I have problem with imports. If try to run flask server it runs ok with relative imports starting with. for ex.  import .logger. But if I want to start app like python3 __main__.py I have error that: ModuleNotFoundError: No module named '__main__.enqueuer'; '__main__' is not a package.

I haven't found any working solution for this problem.

**Comment by hroncok** [comment]
Relative imports are only possible from a "package", not form running a script.

**Comment by hroncok** [comment]
As a good countermeasure, never run `python3 main.py` directly, create the `__main__` module in your package and always run `python3 -m pkgname`.

**Comment by filip-machala** [comment]
Thank you for help, it is working now.
